### ISSUE TITLE
Pharmaceutical dosage change does not show up in MedicationList

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-emed-pmp#10]
We submit an MTP and afterwards a PADV with a dosage change, however the dosage change is afterwards not reflected in the MedicationList and MedicationCard.

GetDocumetReferences shows the MTP, PADV:

MPI-PID:    e7963774-9098-445f-9cab-5d52234b52c3
MTP:  urn:uuid:ccd512dc-ac8e-468b-ab74-ee1e6b6b000c
PADV: urn:uuid:d9812d1a-4562-4053-a497-4ec3bd933e39

PML: https://test.ahdis.ch/mag-pmp/camel/xdsretrieve?uniqueId=urn:uuid:60bf2890-4ac6-46f8-a49a-a3ba8a71a94a&repositoryUniqueId=2.999.756.42.1

See content of files in CDA.

[cda.zip](https://github.com/ahdis/ch-emed-pmp/files/8918405/cda.zip)

@qligier could you have a look please?

**Comment by qligier** [comment]
I've redeployed the aggregator with a better support for PADV documents.
