### ISSUE TITLE
PMP information

### ISSUE THREAD

**Issue by qligier** [ahdis/ch-emed-pmp#11]
CARA Implementation Guide: https://qligier.github.io/cara-emed-ig/
Some CDA-CH-EMED samples: https://github.com/qligier/cdachemed-samples

Endpoints

- ITI-18: services/xds/iti18
- ITI-41: services/xds/iti41
- ITI-43: services/xds/iti43
- ITI-57: services/xds/iti57
- CH:PHARM-1: services/cmpd/chpharm1
- Logs: mhd/logs
- Debug: mhd/debug
- ATNA: mhd/atna

Hosts

- https://pmp.hcuge.ch/pmp/
- https://pmp.posttenebrassilico.ch/pmp/ (temporarily)

**Comment by oliveregger** [comment]
added to http://build.fhir.org/ig/ahdis/ch-emed-pmp/branches/master/index.html
