### ISSUE TITLE
CDA: example GLN with wrong format

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#14]
PMP sets the "Hausarzt" as custodian with a invalid GLN (format). 

``` xml
      <custodian>
        <templateId root="2.16.756.5.30.1.1.10.2.3"/>
        <assignedCustodian>
            <representedCustodianOrganization>
                <id root="2.51.1.3" extension="1.2.3.4"/>
                <name use="L">Hausarzt</name>
            </representedCustodianOrganization>
        </assignedCustodian>
    </custodian>
```

The [FHIR format](https://fhir.ch/ig/ch-core/2.1.0/StructureDefinition-ch-core-gln-identifier.html) checks the correctness of the GLN format. 
_gln-length: GLN must be exactly 13 characters long
gln-modulus-10: GLN must pass the modulus 10 check - https://www.gs1.org/services/how-calculate-check-digit-manually
gln-startswith7601: GLN must start with 7601 for swiss hcp_

If the document is further used for testing purposes, e.g. Analyzer, the GLN must currently be adjusted, otherwise there will be an error during validation.

**Comment by oliveregger** [comment]
@ziegm that could maybe also come from our testdata and the pmp just uses this during the aggregation? for which patient is this?

**Comment by ziegm** [comment]
@oliveregger Patient=MAG011

**Comment by oliveregger** [comment]
@qligier i see it only in responses currently (but I have not all logs completely), could it be that the representedCustodianOrganization gln is not taken over by the pmp? because i see the same 1.2.3.4 also or other patients, where it should have a different it:

https://test.ahdis.ch/eprik-cara-pmp/index.html#/transaction/133a8959-a375-4d7c-9a23-87111b822f66

(ignore the umlaut errors ...)

**Comment by ziegm** [comment]
@qligier 
Could you please tell me what the current status is? I have seen that the GLN has changed (now has the same as the PMP as Device). But the organization's name now is 'Hausarzt', would it not be CARA?

**Comment by qligier** [comment]
Yes, I'll change that in the next deployment.

**Comment by qligier** [comment]
Should be OK now.

**Comment by ziegm** [comment]
yes, it works, thanks!
