### ISSUE TITLE
Unstructured dosage: allow start and end date on dosage

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#16]
* Update mapping
   * information is excluded from the examples at the moment, for following documents:
      * 3a-MTPSintrom (changes in the future)
      * 3c-MTPSintrom (changes in the future)
      * 2g-MTPSimilasan (same start date as document date, end date unknown)
      * 2o-MTPLeggyfix (same start date as document date, end date unknown)
      * 3-3-MTPDermed (same start date as document date, end date unknown)
      * 3-4-MTPExcipial (same start date as document date, end date unknown)
 
* IG cannot be built as CI build with dependency on CH EMED (adjustment of profile dosing unstructured necessary, see [here](http://build.fhir.org/ig/ahdis/ch-emed-pmp/StructureDefinition-ch-emed-pmp-dosage-nonstructured.html)).
   * Sushi: error The element or path you referenced does not exist: dosage[nonstructured].timing.repeat.boundsPeriod.start/end

**Comment by qligier** [comment]
Please note that start and end intake dates in narrative dosage are not supported in CDA-CH-EMED, there's no possible mapping.

**Comment by ziegm** [comment]
@qligier : Thanks for your comment
we plan to submit an request to the ballot (FHIR/CDA) for this purpose

**Comment by ziegm** [comment]
raised issues for ballots:
* CH EMED: https://github.com/hl7ch/ch-emed/issues/127
* CDA CH EMED: https://github.com/hl7ch/hl7ch-cda/issues/18
