### ISSUE TITLE
Patient Instructions not added in the MedicationCard

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-emed-pmp#18]
>The treatment reason and patient medication instructions are updated at each new document
> (i.e. we take the last one) and we put it in the medication card.

I implemented the mapping to Patient Instructions, I see it in the MedicationList (see https://test.ahdis.ch/eprik-cara-pmp/index.html#/transaction/fd9a1611-87ff-4394-8f59-d54de0b0afc6, Response tab)
however not in the generated MedicationCard (https://test.ahdis.ch/eprik-cara-pmp/index.html#/transaction/f8802b4d-9a01-4566-bb70-e56f56142228, Response tab).

**Comment by oliveregger** [comment]
QL: It is implemented but not deployed yet on the test system.

**Comment by ziegm** [comment]
- retested with http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-1-3-MTPTemesta.json.html
- works now (structured medication card and pdf)
