### ISSUE TITLE
Unstructured dosage: allow 'in reserve' on dosage

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#19]
According to the issue #17 about the mapping:
> Update mapping for FHIR element 'Dosage.asNeededBoolean',
> see [profile dosage structured](http://build.fhir.org/ig/ahdis/ch-emed-pmp/StructureDefinition-ch-emed-pmp-dosage-structured.html)
> and [profile dosage unstructured](http://build.fhir.org/ig/ahdis/ch-emed-pmp/StructureDefinition-ch-emed-pmp-dosage-nonstructured.html)

@oliveregger : 
The mapping for the structured dosage works. 
Is the mapping for the unstructured dosage already done and it is even possible/allowed?

***

The IG cannot build the example 3-3-MTPDermed with this element included:
// The element or path you referenced does not exist: dosage[nonstructured].asNeededBoolean
// * dosage[nonstructured][=].asNeededBoolean = true

For testing purposes, the document is adjusted manually accordingly: [Bundle-3-3-MTPDermed_inReserve.zip](https://github.com/ahdis/ch-emed-pmp/files/9357263/Bundle-3-3-MTPDermed_inReserve.zip)
Transformed CDA document: [CDA-3-3-MTPDermed_inReserve.zip](https://github.com/ahdis/ch-emed-pmp/files/9357301/CDA-3-3-MTPDermed_inReserve.zip)

Matchbox: Provide and Register
```json
{
  "response": {
    "status": 400,
    "data": {
      "resourceType": "OperationOutcome",
      "issue": [
        {
          "severity": "error",
          "code": "invalid",
          "details": {
            "coding": [
              {
                "code": "INVALID_DOCUMENT_CONTENT"
              }
            ],
            "text": "The document 'cc2117a2-a547-4415-9fea-c26ea3d8ac44' is not valid: Schematron error: {[[Text@0x4ba1d2ef: content=[(MedicationTreatmentPlanEntryContentModule): choice (hl7:templateId[@root='1.3.6.1.4.1.19376.1.5.3.1.4.7.1']  or  hl7:templateId[@root='1.3.6.1.4.1.19376.1.5.3.1.4.8']  or  hl7:templateId[@root='1.3.6.1.4.1.19376.1.5.3.1.4.9']) does not contain enough elements [min 1x]]]; fpi=null; icon=null; lang=null; see=null; space=null]} in {/hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section/hl7:entry/hl7:substanceAdministration}."
          }
        }
      ]
    }
  },
  "config": {
    "method": "POST",
    "url": "https://test.ahdis.ch/mag-pmp/fhir/",
    "headers": {}
  }
}
```

**Comment by qligier** [comment]
> Is the mapping for the unstructured dosage already done and it is even possible/allowed?

It's currently allowed in CDA, but I don't know if it should.

**Comment by oliveregger** [comment]
have updated the maps accordingly https://github.com/hl7ch/cda-fhir-maps/issues/44

**Comment by oliveregger** [comment]
see https://github.com/hl7ch/ch-emed/issues/117 which has been raised as an issued in github

**Comment by ziegm** [comment]
> have updated the maps accordingly [hl7ch/cda-fhir-maps#44](https://github.com/hl7ch/cda-fhir-maps/issues/44)

If I retry to register the document I get this error:
```json
{
  "response": {
    "status": 400,
    "data": {
      "resourceType": "OperationOutcome",
      "issue": [
        {
          "severity": "error",
          "code": "invalid",
          "details": {
            "coding": [
              {
                "code": "INVALID_DOCUMENT_CONTENT"
              }
            ],
            "text": "The document 'e1f99a0e-3e8d-40fb-aa32-f82e23b10ec2' is not valid: Schematron error: {[[Text@0x75d7e68f: content=[(MedicationTreatmentPlanEntryContentModule): The narrative dosage instructions shall only appear in normal dose regime.]]; fpi=null; icon=null; lang=null; see=null; space=null]} in {/hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section/hl7:entry/hl7:substanceAdministration}."
          }
        }
      ]
    }
  },
  "config": {
    "method": "POST",
    "url": "https://test.ahdis.ch/mag-pmp/fhir/",
    "headers": {}
  }
}
```

**Comment by oliveregger** [comment]
@ziegm was a followup error, can you try again?

**Comment by ziegm** [comment]
> @ziegm was a followup error, can you try again?

@oliveregger it works, thanks
