### ISSUE TITLE
PMP: Unable to find an item entry digest.

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#23]
If I upload this MTP and PADV as HCP it works.
http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-1-3-MTPTemesta.json.html
http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-2-1-PADVTemesta.json.html

If I upload the same documents this way, it doesn't work:
MTP as Patient
**PADV as HCP**
error: The document '13bc2947-10c8-4e94-8dac-0629a0c5329f' is not valid: **Unable to find an item entry digest.**
see also https://test.ahdis.ch/eprik-cara-pmp/index.html#/transaction/8a32b5e4-48c3-48be-9bcc-e45508b13eda

@qligier: shouldn't this also work or is my expectation wrong?

**Comment by qligier** [comment]
While converting the MTP with matchbox, I get the error: "HAPI-0389: Failed to call access method: org.hl7.fhir.exceptions.FHIRException: Parsing FHIR content returned multiple elements in a context where only one element is allowed"

**Comment by qligier** [comment]
The referenced MTP document/item (7ADE729C-A8C6-4B23-8DAA-2C78A22CE153) is not registered in the PMP. In theory it should work the same way, yes.

**Comment by ziegm** [comment]
@oliveregger 
When I upload an MTP as a patient, Matchbox assigns a new UUID to the document.
If I then switch to HCP and upload a PADV, do I need to use the "old" or "new" UUID for document referencing there?

**Comment by qligier** [comment]
> I can't reproduce this error.

Here's the request I send. Am I doing something wrong? [request_http.txt](https://github.com/ahdis/ch-emed-pmp/files/9626039/request_http.txt)

**Comment by qligier** [comment]
> @oliveregger When I upload an MTP as a patient, Matchbox assigns a new UUID to the document. If I then switch to HCP and upload a PADV, do I need to use the "old" or "new" UUID for document referencing there?

Hmm, changing UUIDs seems a dangerous thing to do in a middleware, you would need to keep a map of changed UUIDs to also rewrite the document contents.

**Comment by ziegm** [comment]
> > I can't reproduce this error.
> 
> Here's the request I send. Am I doing something wrong? [request_http.txt](https://github.com/ahdis/ch-emed-pmp/files/9626039/request_http.txt)

but this is the padv not the mtp?

**Comment by qligier** [comment]
I also tried the PADV and I got the same error.
Here is the MTP request: [request_mtp_http.txt](https://github.com/ahdis/ch-emed-pmp/files/9626092/request_mtp_http.txt)

**Comment by oliveregger** [comment]
@qligier you need to set the content-type to fhir+json:  Content-Type: application/fhir+json;fhirVersion=4.0

**Comment by qligier** [comment]
Damn! I saw this and "fixed" it to `application/json+xml;fhirVersion=4.0`... It's working fine now, thanks!

**Comment by oliveregger** [comment]
> 



> When I upload an MTP as a patient, Matchbox assigns a new UUID to the document.
> If I then switch to HCP and upload a PADV, do I need to use the "old" or "new" UUID for document referencing there?

@ziegm the matchbox tooling replaces all uuids during the session, it is displayed as a list, do you see it still when changing to hcp?

**Comment by oliveregger** [comment]
> Hmm, changing UUIDs seems a dangerous thing to do in a middleware, you would need to keep a map of changed UUIDs to also rewrite the document contents.

this is only for testing via the GUI, not middleware .... we rewrite all uuid's otherwise we cannot test the different usecase we described

**Comment by ziegm** [comment]
> > 
> 
> > When I upload an MTP as a patient, Matchbox assigns a new UUID to the document.
> > If I then switch to HCP and upload a PADV, do I need to use the "old" or "new" UUID for document referencing there?
> 
> @ziegm the matchbox tooling replaces all uuids during the session, it is displayed as a list, do you see it still when changing to hcp?

@oliveregger no, the list isn't displayed after the change

**Comment by oliveregger** [comment]
then this is the problem in the testing gui we have to fix, i will open an issue for it in matchbox
