### ISSUE TITLE
publish a padv as hcp to a mtp (published as hcp) does not work

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#24]
[2.1.1 CH EMED - UC Step 1-1 and PADV description: change posology](https://github.com/ahdis/ch-emed-pmp/wiki/Test-Cases#21-padv-change)
* [1-1-MTP-Triatec](http://fhir.ch/ig/ch-emed/Bundle-1-1-MedicationTreatmentPlan.json.html): 0.5-0-0-0 
* [1-x-PADV-Triatec](http://fhir.ch/ig/ch-emed/Bundle-PharmaceuticalAdvice-ChangeDosage.json.html): 1-0-0-0

MAGMED010 (targetId: Patient/2.16.756.5.30.1.191.1.0.2.1-68e0258d-20c6-4f6c-8740-00e9e0f0d29f)

MTP: urn:uuid:c9f758a1-296c-4710-84d4-e181db8c7478 -> urn:uuid:45cd122e-1ccb-4b79-8465-9f464acf2232
PADV: urn:uuid:adab8d2d-ae14-48d6-8d15-b726d6ea82c5 -> urn:uuid:9379eac9-99a3-453b-8a71-8b880b51aba0

```json
{
  "response": {
    "status": 400,
    "data": {
      "resourceType": "OperationOutcome",
      "issue": [
        {
          "severity": "warning",
          "code": "invalid",
          "details": {
            "coding": [
              {
                "code": "EXTRA_METADATA_NOT_SAVED"
              }
            ],
            "text": "DocumentEntry.sourcePatientInfo has not been saved"
          }
        },
        {
          "severity": "error",
          "code": "invalid",
          "details": {
            "coding": [
              {
                "code": "INVALID_DOCUMENT_CONTENT"
              }
            ],
            "text": "The document '9379eac9-99a3-453b-8a71-8b880b51aba0' is not valid: A patient or their representatives are allowed to publish a PADV document with a code that is not COMMENT only if the referenced document was published by themself of their representatives. [PMP (6.4.2.2)]."
          }
        },
        {
          "severity": "error",
          "code": "invalid",
          "details": {
            "coding": [
              {
                "code": "INVALID_DOCUMENT_CONTENT"
              }
            ],
            "text": "The document '9379eac9-99a3-453b-8a71-8b880b51aba0' is not valid: A patient or their representatives are allowed to publish a PADV document with a code that is not COMMENT only if the referenced document was published by themself of their representatives. [PMP (6.4.2.2)]."
          }
        }
      ]
    }
  },
  "config": {
    "method": "POST",
    "url": "https://test.ahdis.ch/mag-pmp2/fhir/",
    "headers": {}
  }
}
```

**Comment by qligier** [comment]
Could you provide me with the transaction content (SAML assertion and metadata), please?

Also, the error should not appear twice.

**Comment by ziegm** [comment]
> Could you provide me with the transaction content (SAML assertion and metadata), please?
> 
> Also, the error should not appear twice.

https://test.ahdis.ch/eprik-proxy-cara/index.html#/transaction/b8fa9cc5-72a8-44a9-9b92-99ba52c92a24

**Comment by qligier** [comment]
I've redeployed with a fix.

**Comment by ziegm** [comment]
Retested and works as expected, thanks!
