### ISSUE TITLE
Missing Composition.section 'medication use' when patient does not have medications

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#25]
We were expecting this section in the medication card. It is missing when the patient does not have medications.

For example: CHUV001 (Aegerter-Bischoff, BRUNO KAKOB)

The old medication card contains this section.

{
						"title": "Liste de médicaments",
						"code": {
							"coding": [
								{
									"system": "http://loinc.org",
									"code": "10160-0",
									"display": "History of medication use"
								}
							]
						},
						"text": {
							"status": "generated",
							"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\" id=\"narrative\">See the PDF original representation</div>"
						}
					}

**Comment by qligier** [comment]
I've redeployed with a fix.

**Comment by arhuberg** [comment]
Hi - is the system back up?

I am unable to get to https://pmp.posttenebrassilico.ch/pmp/mhd/logs

and getting a 503 on the [findMedication](https://test.ahdis.ch/mag-pmp2/fhir/DocumentReference/$find-medication-list)

1/12/2023, 10:05:13 AM	xds-iti18	SOAP → HTML	POST	/pmp2/services/cmpd/chpharm1	Http-Status 503Response invalid

**Comment by arhuberg** [comment]
Verified 12 Jan 2023 1109 AM EST
![image](https://user-images.githubusercontent.com/122478371/212119975-4c4f7777-3df5-4901-ad1f-c652c483491f.png)

**Comment by qligier** [comment]
Sorry for the Tomcat crash!
Does the screen mean it's properly solved for you?
