### ISSUE TITLE
ITI-65 returns error when handling PADV with comments

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#27]
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "warning",
    "code": "invalid",
    "details": {
      "coding": [ {
        "code": "EXTRA_METADATA_NOT_SAVED"
      } ],
      "text": "DocumentEntry.sourcePatientInfo has not been saved"
    }
  }, {
    "severity": "error",
    "code": "invalid",
    "details": {
      "coding": [ {
        "code": "REGISTRY_ERROR"
      } ],
      "text": "The PMP has encountered an internal error while aggregating the CDA document '5f8dd3db-ccb7-432b-84c3-06727d4f0cf8', item: 'efd21f98-69d9-4b38-9a1d-7af7043240b9'"
    }
  } ]
}

**Comment by arhuberg** [comment]
[padvwithchange.zip](https://github.com/ahdis/ch-emed-pmp/files/10404938/padvwithchange.zip)

**Comment by arhuberg** [comment]
g.pmp.application.listeners.PatientDemographicsEncounterListener.onApplicationEvent(ch.qligier.hug.pmp.common.models.events.PatientDemographicsEncounterEvent)
[2023-01-12 18:25:28] [info] org.hibernate.NonUniqueObjectException: A different object with the same identifier value was already associated with the session : [ch.qligier.hug.pmp.storag

**Comment by qligier** [comment]
The PMP is not handling the Observation.note.author properly. I'll fix this bug next week!

**Comment by qligier** [comment]
I've redeployed with a fix.

**Comment by arhuberg** [comment]
When I sent a new PADV, I received this response:
{
	"resourceType": "OperationOutcome",
	"issue": [
		{
			"severity": "warning",
			"code": "invalid",
			"details": {
				"coding": [
					{
						"code": "EXTRA_METADATA_NOT_SAVED"
					}
				],
				"text": "DocumentEntry.sourcePatientInfo has not been saved"
			}
		},
		{
			"severity": "error",
			"code": "invalid",
			"details": {
				"coding": [
					{
						"code": "REGISTRY_ERROR"
					}
				],
				"text": "The PMP has encountered an internal error while aggregating the eMed document 'bd779117-070b-4e32-8c2c-051965b918f3', item: '1c950959-a20c-4b6b-a41c-4506786cd462'"
			}
		}
	]
}

**Comment by arhuberg** [comment]
When I check the logs, I saw this error now maybe related to: https://github.com/ahdis/ch-emed-pmp/issues/32

[2023-01-17 16:38:05] [info] java.lang.NullPointerException: Cannot invoke "java.util.Date.toInstant()" because the return value of "org.hl7.fhir.r4.model.Annotation.getTime()" is null

**Comment by qligier** [comment]
Redeployed with a fix.

**Comment by arhuberg** [comment]
Tested Fix 10:57 EST Jan 18
