### ISSUE TITLE
Delete document does not work

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#28]
@qligier 
MAGMED010 (Loris Bertrand PALOLA, 1995-05-23), MPI-ID: 68e0258d-20c6-4f6c-8740-00e9e0f0d29f

I tried to delete the documents (MTP) and it didn't work. The server responds with:
`"text": "The document is not at the end of its medication chain(s) [PMP (6.4.2.5)]."`

https://test.ahdis.ch/eprik-proxy-cara/index.html#/transaction/f4237a8c-13c6-447f-bf1d-c1cd2517bbbe

Something seems to be mixed up on the server. Do you see anything and how can it be cleaned up?

**Comment by qligier** [comment]
Yep, wrong condition in the SQL query.

**Comment by qligier** [comment]
I've redeployed with a fix.

**Comment by ziegm** [comment]
Perfect, thanks!
