### ISSUE TITLE
Issues in Medication List document

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#29]
There are a few issues with the MedicationList (maybe already known):

* MedicationStatement.informationSource: minimum required = 1, but only found 0
* Composition.section:list.title: minimum required = 1, but only found 0 
* Composition.section:list.text: minimum required = 1, but only found 0 

Tested use case:
* MAGMED010 (Loris Bertrand PALOLA, 1995-05-23), MPI-ID: 68e0258d-20c6-4f6c-8740-00e9e0f0d29f
* [2.1 PADV: CHANGE
](https://github.com/ahdis/ch-emed-pmp/wiki/Test-Cases#21-padv-change)
   * 2.1.1 CH EMED - UC Step 1-1 and PADV description: change posology
      * [1-1-MTP-Triatec](http://fhir.ch/ig/ch-emed/Bundle-1-1-MedicationTreatmentPlan.json.html): 0.5-0-0-0 (Retest 13.01.2023)
      * [1-x-PADV-Triatec](http://fhir.ch/ig/ch-emed/Bundle-PharmaceuticalAdvice-ChangeDosage.json.html): 1-0-0-0 (Retested 13.01.2023)

**Comment by ziegm** [comment]
In CARD and PRE the minimum cardinality is 0 (changed in May 2021, see [commit](https://github.com/hl7ch/ch-emed/commit/7f747bf3c043b0d64efc24c702ab6b1632931f1b#diff-9ef6165518fa08e7080fdaf9b2a3b64c2171dad49727862b9ebf4ce062034685)).
This is because these two documents have a required original representation (PDF) and the other ones don't.
Is that correct @oliveregger ?

**Comment by oliveregger** [comment]
origin why it was required: https://hl7.org/fhir/composition-definitions.html#Composition.section.text
what is the narrative for the Medication List? QL will generate a summary for section:list.text

**Comment by qligier** [comment]
Redeployed with a better support for PML documents.
