### ISSUE TITLE
MTP validation inconsistency

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#30]
Executed the validator against an MTP...

One of the warnings found was: "The display \"Medication treatment plan.brief\" is not a valid display for the code {http://loinc.org}77604-7 - should be one of ['Medication treatment plan.brief Document', 'Med tx plan.brief Doc'

Corrected the issue, and when running the validator on the new document we see "Does not match slice 'treatmentPlan' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '77604-7') and (display = 'Medication treatment plan.brief')).exists())"

Observed similar behavior with the PADV.

**Comment by arhuberg** [comment]
[mtp-validation-before.zip](https://github.com/ahdis/ch-emed-pmp/files/10412036/mtp-validation-before.zip)
[mtp-validation-after.zip](https://github.com/ahdis/ch-emed-pmp/files/10412037/mtp-validation-after.zip)

**Comment by qligier** [comment]
Yep, there are multiple places in the profile where the display is not part of "official" displays, as per the SNOMED CT version loaded by the FHIR validator.
@ziegm Should we fix these in the profile?

**Comment by ziegm** [comment]
@oliveregger
shouldn't it be solved at the validator?

**Comment by oliveregger** [comment]
this warnings can't be removed from the validato.

either the profiles are adapted, and if not possible (the display names were taken from the IHE specification) we have to live with the warnings.

**Comment by oliveregger** [comment]
For the validation you can turn off the terminology server with the option txServer set to n/a, then it will not produce those warnings.

**Comment by ziegm** [comment]
> this warnings can't be removed from the validato.
> 
> either the profiles are adapted, and if not possible (the display names were taken from the IHE specification) we have to live with the warnings.

Opened an issue to relax the cardinality (no fixedValues in patternCodeableConcepts):
https://github.com/hl7ch/ch-emed/issues/194

**Comment by oliveregger** [comment]
a) use the official display  names in the specificatin if possible
b) don't use the display text for the pattern or fixedCodeableConcept, leave the warnings to the terminology service. 

telco 18.1.2022: support his change in ch-emed
