### ISSUE TITLE
How to associate a device with the MTP or PADV composition

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#31]
The validator is returning an error on the Device resource:
"Entry 'urn:uuid:408c556f-353e-48b8-8475-1ebe9af04a3b' isn't reachable by traversing links (forward or backward) from the Composition"

Previously, we could refer to the Device resource using the author. The previous version supported a choice from the following resources:
PractitionerRole
Patient
Practitioner
Device
RelatedPerson
Organization

The new version of the spec has the author element with a choice from the following:
PractionerRole
Patient
RelatedPerson

**Comment by arhuberg** [comment]
OK makes sense. 
Any thoughts to how to avoid the validation error?

**Comment by qligier** [comment]
The error means that this resource (which has been added to the Bundle), is not referenced in the Composition, or in another Resource which is referenced in the Composition. To solve it, you can either remove it from the Bundle, or add a reference to it in another Resource.

**Comment by arhuberg** [comment]
I added for it supportability reasons so that we would know which version of software created the document.

Anyone have any thoughts about which resource to add it too? Just wanted to be consistent if others were adding a Device as well. During the projectathon, the medication cards we received encoded a Device - that is where I thought it was a good idea.

**Comment by qligier** [comment]
In that case, what you could do is fill the Composition.section:annotation with your debug information. You must provide a text, and may reference your device as author here (or may simply add this information in the text, it would be more lightweight).
That is, unless your software may want to fill another information in here (although I have not seen a convincing use case for that section yet).

**Comment by ziegm** [comment]
> I added for it supportability reasons so that we would know which version of software created the document.
> 
> Anyone have any thoughts about which resource to add it too? Just wanted to be consistent if others were adding a Device as well. During the projectathon, the medication cards we received encoded a Device - that is where I thought it was a good idea.

Opened an issue in CH EMED to introduce an additional slice for the device:
https://github.com/hl7ch/ch-emed/issues/195

**Comment by oliveregger** [comment]
Telco 18.1: support the ch-emed #195
