### ISSUE TITLE
Add a PADV - XDSRegistryError

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#32]
@qligier could you please have a look:
https://test.ahdis.ch/eprik-proxy-cara/index.html#/transaction/515769fb-0d21-423e-8a5d-48ae0c06f1cf

(Testing use case step 2.2.1: https://github.com/ahdis/ch-emed-pmp/wiki/Test-Cases#22-padv-cancel)

**Comment by qligier** [comment]
It seems a silly mistake of mine:
```log
java.lang.NullPointerException: Cannot invoke "java.util.Date.toInstant()" because the return value of "org.hl7.fhir.r4.model.Annotation.getTime()" is null
	at ch.qligier.hug.pmp.emed.aggregators.PadvAggregator.aggregate(PadvAggregator.java:124)
```

**Comment by ziegm** [comment]
thanks, tested and works!
