### ISSUE TITLE
Error with LIST validation

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#33]
Bundle.entry[0]: Bundle.entry[0].resource.section[0].entry[0]: Bundle.entry[0].resource.section[0].entry[0]: Bundle.entry[4].resource: MedicationStatement.contained: max allowed = 1, but found 4 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement-list|3.0.0)

Will be fixed in CH EMED: https://github.com/hl7ch/ch-emed/issues/196

@qligier 
I noticed that some of the contained resources had the same IDs (e.g. #1 twice), this cannot be resolved.

**Comment by qligier** [comment]
> I noticed that some of the contained resources had the same IDs (e.g. https://github.com/ahdis/ch-emed-pmp/issues/1 twice), this cannot be resolved.

Yes, I need to iterate over all resources to fix their ID because of HAPI. I have done it for the medication card, will do for the medication list.

**Comment by ziegm** [comment]
> > I noticed that some of the contained resources had the same IDs (e.g. #1 twice), this cannot be resolved.
> 
> Yes, I need to iterate over all resources to fix their ID because of HAPI. I have done it for the medication card, will do for the medication list.

@qligier when would you be able to fix this point? I am currently working with the list documents and have to adapt it each time manually.

**Comment by qligier** [comment]
I'm working on it, but an old issue in Hapi means I've to update IPF and Husky, updating indirectly pretty much all dependencies of the project. Quite a few changelogs to read, I hope it's done by the end of the week!

**Comment by ziegm** [comment]
> I'm working on it, but an old issue in Hapi means I've to update IPF and Husky, updating indirectly pretty much all dependencies of the project. Quite a few changelogs to read, I hope it's done by the end of the week!

Oh... Thanks for the info, that's totally fine for me!

**Comment by qligier** [comment]
Redeployed with a better support for PML documents.
