### ISSUE TITLE
Free text dose missing from Medication Card PDF

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#36]
The dose (when unstructured) is not presented in the PDF.

For example (dosage.text).
"dosage": [ {
	        "id": "#dosage-1",
	        **"text": "5 mg = 1 cpr à 08:00, 2.5 mg = 0.5 cpr à 14:00, 5 mg = 1 cpr à 18:00, PO, 3 x / j - Tous les jours *",**
	        "patientInstruction": "with food or milk to prevent stomach upset"
	      }

**Comment by arhuberg** [comment]
![image](https://user-images.githubusercontent.com/122478371/213521575-1e0e004e-fda4-4d4e-b838-39b32d5ced88.png)

**Comment by arhuberg** [comment]
Should the prescriber be visible on the PDF?

**Comment by qligier** [comment]
Indeed, it should be the _text_, not the _patientInstructions_. I've deployed a fix.

**Comment by arhuberg** [comment]
I verified the dose.text is shown on the PDF.

However, I think 'patientInstructions' should appear as well correct?

**Comment by qligier** [comment]
Probably, but I'm not sure how. I'll ask.

**Comment by arhuberg** [comment]
Do you want to close this and I will open an issue for the patient instructions?

**Comment by qligier** [comment]
I've opened #37 for that!
