### ISSUE TITLE
Patient instructions in the medication card PDF

### ISSUE THREAD

**Issue by qligier** [ahdis/ch-emed-pmp#37]
Should the patient instructions be displayed in the medication card PDF, and if so, how?

**Comment by CBehrend-cpu** [comment]
Yes, please display the patient instructions. How: I would guess in the same grey line as "À prendre dès le 26/01/2023" or in separate line below.

**Comment by qligier** [comment]
In the medication card, the column "raison du traitement" is renamed to "commentaire" and now contains the treatment reason plus the patient instructions.
https://github.com/project-husky/husky/commit/ab14f281f1b08044f287a6f056ecefd91ba48891
I've redeployed with that change.

**Comment by CBehrend-cpu** [comment]
Thanks!
