### ISSUE TITLE
LIST: unknown extension in entries because of meta.profile

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#38]
Slicing information (This element does not match any known slice defined in the profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement) in the validation of a Medication List document.
In the element meta.profile is the ch-emed-medicationstatement, not the more specific ch-emed-medicationstatement-list specified (also for the other entry types). That could be changed, to avoid the slicing information...

``` json
               "meta": {
                    "profile": [
                        "http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement",
                        "http://hl7.org/fhir/StructureDefinition/MedicationStatement"
                    ]
                },
```

``` json
               "meta": {
                    "profile": [
                        "http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-observation",
                        "http://hl7.org/fhir/StructureDefinition/Observation"
                    ]
                },
```
etc.

**Comment by qligier** [comment]
Indeed, this one is an easy fix. It will be included in the next release.

**Comment by qligier** [comment]
Redeployed with a better support for PML documents.
