### ISSUE TITLE
Cannot delete document

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#41]
https://test.ahdis.ch/eprik-proxy-cara/index.html#/transaction/35292bbe-b05a-4b5b-b6af-8f8705c68bac
"The document is not at the end of its medication chain(s) [PMP (6.4.2.5)]"

It's an MTP document, which I cannot delete. The Medication Card shows no medication.

@qligier Could you please have a look what the problem here might be?

**Comment by qligier** [comment]
There was a ghost PADV entry for that patient, I don't know how it happened. I hope it was caused by my manual interventions in the database, but I'll try to reproduce the behavior in case it is a real bug.
