### ISSUE TITLE
LIST: Composition.type -> LOINC

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#44]
@qligier FYI: 
https://github.com/hl7ch/ch-emed/issues/206: The medication list document would now need (additionally) the LOINC code for Composition.type.

**Comment by qligier** [comment]
Updated in https://github.com/project-husky/husky/commit/da43eeec2b4fb6058b7d3a170e5f48ed91f82374 and https://github.com/project-husky/husky/commit/f6a5e42d8d6cea9461813573029739b7d6c44e08.
