### ISSUE TITLE
QUESTION: boundsPeriod start / stop granularity

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#45]
From the CARA integration guide: "Must support. The intake start and stop date (with or without time) is given by the first <hl7:effectiveTime>, with type IVL<TS.CH.TZ>. Boundaries are inclusive. The dates SHOULD be precise to the day (YYYYMMDD); there SHOULD be a good reason to be more precise than that."

The CARA guide does not define a minimum supported? Is there a minimum? Is year and/or year-month only supported? It is allowed in the FHIR specification - "dateTime | A date, date-time or partial date (e.g. just year or year + month)"?

**Comment by qligier** [comment]
> Is year and/or year-month only supported?

It was allowed in CDA and still is in FHIR, but I am uncertain if there is a real use case here? What will patients do if dates are only precise to the year or month? That seems dangerous to me.

**Comment by arhuberg** [comment]
When a clinician documents a home or discharge medication, our system (Soarian Clinicals) requires the date and time.

However, there could be an edge case where a medication is documented for the first time - the patient answers this question: When did you start your high blood pressure medication - answer: 2010 (maybe July 2010)... 

But in our system, we will always have a date (and time), but we just output the date. Was just curious what other systems may do.

I guess the HAPI API makes it easy - because it returns the value as a java.util.Data - if only "2020" is in the period.start, then we will read Jan 01, 2020 00:00.

**Comment by qligier** [comment]
After discussion with Stéphane: we won't restrict the granularity. The recommendation is to use `YYYYMMDD`, any other granularity should have a good reason to be used.
Beware with stop dates, "2020" should be evaluated as "Dec 31 2020, 23h59" (because it is inclusive). I am unsure if HAPI gets it right.
See https://build.fhir.org/ig/CARA-ch/ch-emed-epr/guidance_datatypes.html.

**Comment by arhuberg** [comment]
If the start or end was "2012", the HAPI API returns Sun Jan 01 00:00:00 EST 2012 - it is not aware of the inclusive meaning of stop.

Thanks of the info.

**Comment by arhuberg** [comment]
I think this can be closed.
