### ISSUE TITLE
ITI-65 for CHUV001-010 patients returns a "UNKNOWN_PATIENT_ID"

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#46]
Here is an example:
CHUV001
CommunityPatientID=64370848-bed5-46c4-972f-05b410b59235
https://test.ahdis.ch/eprik-cara/index.html#/transaction/2fc3847e-3b07-40c7-a260-4f12bd741fff

**Comment by arhuberg** [comment]
Another example:
MAGMED005
7a4ec59f-a024-4cfb-bc04-3339c53cb9ac
https://test.ahdis.ch/eprik-cara/index.html#/transaction/f537ccc7-9004-4962-b6ad-bcef4469507a

**Comment by qligier** [comment]
I have to whitelist your TCU, it is blocked. Those patients have an open record.

**Comment by arhuberg** [comment]
OK - Tell me when it gets whitelisted.

Just curious, what changed our TCU be be blocked?

**Comment by qligier** [comment]
I've redeployed. There was no TCU whitelist before

**Comment by arhuberg** [comment]
The error is different now:
https://test.ahdis.ch/eprik-cara/index.html#/transaction/bedd3bda-bc39-4e9d-ba71-bc2746632021

Last REST Response={
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "warning",
    "code": "invalid",
    "details": {
      "coding": [ {
        "code": "EXTRA_METADATA_NOT_SAVED"
      } ],
      "text": "DocumentEntry.sourcePatientInfo has not been saved"
    }
  }, {
    "severity": "error",
    "code": "invalid",
    "details": {
      "coding": [ {
        "code": "REGISTRY_ERROR"
      } ],
      "text": "Unexpected exception while processing the request"
    }
  } ]
}

**Comment by qligier** [comment]
Yep, sorry, I've deployed a new fix for that.

**Comment by arhuberg** [comment]
Thanks. Working as expected.
