### ISSUE TITLE
Medication Card: Unable to retrieve medication card ITI-68 when dose is not structured

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#48]
Unable to retrieve medication card ITI-68 when dose is not structured. 

See patient:
CHUV001
Aegerter-Bischoff, BRUNO KAKOB 
https://test.ahdis.ch/eprik-cara/index.html#/transaction/b4908cd6-8477-4ec9-8b4b-8b6a1f3c7b13
An unexpected exception occurred (3f44d3f7)

It appears the issue is related to the dosage we submitted with an MTP (See below).

In this example, we have a coded route and frequency, but NOT a dose. Is this medication card builder expecting a structured/coded dose/rate if there is a code frequency?

We are just changing how we encode dosage element - previously we only created a structure dosage if all elements (frequency, route, and dose were coded; but, now we are changing to encode what we have (partial dosage).

"dosage": [
	{
		"text": "750 MG/DOSE (10 mg/kg/dose), PO, * Max. 3x/j - Tous les jours *",
		"patientInstruction": "with food",
		"timing": {
			"repeat": {
				"boundsPeriod": {
					"start": "2023-03-06"
				},
				"when": [
					"MORN",
					"NOON",
					"EVE"
				]
			}
		},
		"asNeededBoolean": true,
		"route": {
			"coding": [
				{
					"system": "urn:oid:0.4.0.127.0.16.1.1.2.1",
					"code": "20053000",
					"display": "Oral use"
				}
			]
		}		
       }
]

**Comment by qligier** [comment]
Good catch, a frequency without a dose is allowed by the specifications, but is not expected by the aggregator.

I think it should be allowed, but then the medication card needs to be adjusted. What would be shown in that case? We can't fill the usual four columns. And it can't be all narrative because the frequency may not be transcribed (as it is the case in your example).

**Comment by qligier** [comment]
Same question for the reversed situation, a dose without frequency.

**Comment by qligier** [comment]
HUG (STS+LZK): In both cases, the medication card will display the information as narrative only, without using the 4 columns.

**Comment by arhuberg** [comment]
Repeated test and verified it works as expected. This can be closed.
