### ISSUE TITLE
Patient demographics changing in pdf after documents are exported to CARA (Cheri Gey)

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#50]
Reported from @cherigey
After documents are exported to CARA, we noticed the patient name was changed to the Soarian patient name on the pdf on a subsequent import. We tested a bit further and have found the same happens with gender and date of birth.

**Comment by qligier** [comment]
The aggregator has two sources of demographic information: CARA's MPI and eMedication documents. The MPI is used to initiate the record, then the aggregator will use demographics found in eMedication documents to keep it up-to-date.

Demographics are given and family name(s), the birthdate, gender and local IDs.

**Comment by CheriGey** [comment]
We tested the change on the Cerner side and looks good.  Exported patient demographics are no longer updating the MPI.
