### ISSUE TITLE
Next deployment

### ISSUE THREAD

**Issue by qligier** [ahdis/ch-emed-pmp#53]
The next version of the PMP is now ready. It is a major release, with quite a few changes:

- The validator is now **strict**.
- New dosage recommendations ([1](https://github.com/hl7ch/ch-emed/pull/218) & [2](https://github.com/hl7ch/ch-emed/pull/217)).
- The [patient's weight](https://github.com/CARA-ch/ch-emed-epr/pull/5) is now supported.
- The PMLC now contains a [reference to the prescription](https://github.com/CARA-ch/ch-emed-epr/pull/6).
- Internal: the aggregation model has changed, it requires a **database wipe**.

@rhallowell @arhuberg @ziegm @oliveregger When can I redeploy the PMP? Do you have time constraints?

**Comment by qligier** [comment]
The next deployment is planned on Monday, the 24th, morning.

**Comment by qligier** [comment]
The MobileAccessGateway has been redeployed: https://test.ahdis.ch/mag-pmp2/#/mag
The PMP aggregator has been redeployed.

**Comment by arhuberg** [comment]
Hi,

When running the validator I received this error – is the validator available?
{   "resourceType": "OperationOutcome",   "issue": [ {     "severity": "error",     "code": "processing",     "details": {       "coding": [ {         "system": http://hl7.org/fhir/java-core-messageId       } ]     },     "diagnostics": "Validation for profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan not supported by this server, but additional ig's could be configured.",     "location": [ "Line[0] Col[0]", "Line 0, Col 0" ]   } ] }

Tony

From: Quentin Ligier ***@***.***>
Sent: Monday, April 24, 2023 4:07 AM
To: ahdis/ch-emed-pmp ***@***.***>
Cc: Anthony Rhuberg ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [ahdis/ch-emed-pmp] Next deployment (Issue #53)


The MobileAccessGateway has been redeployed: https://test.ahdis.ch/mag-pmp2/#/mag<https://urldefense.com/v3/__https:/test.ahdis.ch/mag-pmp2/*/mag__;Iw!!ACWV5N9M2RV99hQ!Ii-sLqK0Qgr39qwVWH17V7mMxXyYmeATJ_cf_mZaCg46MWYk0iVqDN407f7xi2VWaYcf7ktVk2fmf_fR6_npyraDlrB5_w$>
The PMP aggregator has been redeployed.

**Comment by qligier** [comment]
Hi Tony,
Which validator?

**Comment by arhuberg** [comment]
MTP and PADV validator

/matchboxv3/fhir/$validate

From: Quentin Ligier ***@***.***>
Sent: Monday, April 24, 2023 8:32 AM
To: ahdis/ch-emed-pmp ***@***.***>
Cc: Anthony Rhuberg ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [ahdis/ch-emed-pmp] Next deployment (Issue #53)


Hi Tony,
Which validator?

**Comment by qligier** [comment]
I've opened https://github.com/ahdis/matchbox/issues/104

**Comment by oliveregger** [comment]
if you add the version to the profile for validation (|3.0.0) it works, have to analyze why it doest not work with the current version

**Comment by qligier** [comment]
Selecting _ch.fhir.ig.ch-emed#3.0.0_ in "Validate against specific IG" works.
