### ISSUE TITLE
Unable to retrieve medication card after a PADV

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#56]
I sent an MTP for CHIUV010 and then a PADV. I then retrieved the medication card and received an error.

https://test.ahdis.ch/eprik-cara/index.html#/transaction/858b005f-ac25-4cbd-9c4f-15de71a8c200
For example:
	{
	  "headers": {
	    "normalizedNames": {},
	    "lazyUpdate": null
	  },
	  "status": 400,
	  "statusText": "Bad Request",
	  "url": "https://test.ahdis.ch/mag-pmp2/camel/xdsretrieve?uniqueId=urn:uuid:876440c2-108b-4b4a-b159-f118612310ac&repositoryUniqueId=2.999.756.42.1",
	  "ok": false,
	  "name": "HttpErrorResponse",
	  "message": "Http failure response for https://test.ahdis.ch/mag-pmp2/camel/xdsretrieve?uniqueId=urn:uuid:876440c2-108b-4b4a-b159-f118612310ac&repositoryUniqueId=2.999.756.42.1: 400 Bad Request",
	  "error": "An unexpected exception occurred (5710e2e9)"
	}

**Comment by qligier** [comment]
Yep, for some reason, a note author cannot be a PractitionerRole. I've modified the aggregator to use the Practitioner in that case, and redeployed. Can you delete the PADV and re-send it please?

**Comment by arhuberg** [comment]
I deleted all documents on CHUV010 and submitted a MTP followed by a PADV-CHANGE. 

Got the error here: https://test.ahdis.ch/eprik-cara/index.html#/transaction/c6935b50-3654-4601-a601-b9d5ca568a38

**Comment by qligier** [comment]
Bad code in Husky, it is not expecting a Device as first Composition author. I will patch that.

**Comment by qligier** [comment]
I've redeployed, with fixes for other issues I've encountered while debugging. Hopefully it works properly now...

**Comment by arhuberg** [comment]
Great. Working as expected. We will continue to test too.
