### ISSUE TITLE
Unable to save MTP

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#57]
Although the title is the same, this seems to be a different issue.

https://test.ahdis.ch/eprik-cara/index.html#/transaction/f11fc75c-cc8e-4632-be73-6266c3331623

I attached the MTP.json that is failing - it passed validation.

[mtp.zip](https://github.com/ahdis/ch-emed-pmp/files/11402714/mtp.zip)

**Comment by arhuberg** [comment]
These are the validation results:
java -jar c:\tmp\validator_cli.jar c:\tmp\mtp.json -version 4.0.1 -profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan -ig ch.fhir.ig.ch-emed#current
FHIR Validation tool Version 5.6.92 (Git# dc677cad51a2). Built 2023-01-20T22:59:09.486Z (104 days old)
  Java:   17.0.6 from C:\jdk-17.0.6 on amd64 (64bit). 8116MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = C:\Engineering\SC\CS-SC-TRUNK-ORD-JAVAONLY-DEV, Package Cache = C:\Users\ar037601\.fhir\packages
  Params: c:\tmp\mtp.json -version 4.0.1 -profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan -ig ch.fhir.ig.ch-emed#current
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1.: - 4576 resources (00:04.035)
  Load hl7.terminology#5.1.0 - 4180 resources (00:02.061)
  Load R5 Extensions - 0 resources (00:01.430)
  Terminology server http://tx.fhir.org - Version 2.1.0 (00:00.736)
  Load hl7.terminology.r4#5.0.0 - 4174 resources (00:00.967)
  Load ihe.formatcode.fhir#1.1.0 - 2 resources (00:00.097)
  Load ch.fhir.ig.ch-epr-term#2.0.8 - 33 resources (00:00.001)
  Load ch.fhir.ig.ch-core#current - 98 resources (00:00.006)
  Load ch.fhir.ig.ch-emed#current - 52 resources (00:00.002)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.0.12, hl7.terminology#5.1.0, hl7.terminology.r4#5.0.0, ihe.formatcode.fhir#1.1.0, ch.fhir.ig.ch-epr-term#2.0.8, ch.fhir.ig.ch-core#current, ch.fhir.ig.ch-emed#current]
  Get set...  go (00:01.048)
Validating
  Profiles: [http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan]
  Validate c:\tmp\mtp.json
Validate Bundle against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan|3.1.0Validate Composition against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-composition-medicationtreatmentplan|3.1.0Validate PractitionerRole against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-practitionerrole|3.1.0..........20..........40..........60..........80.........|
Validate Device against http://hl7.org/fhir/StructureDefinition/Device|4.0.1..........20..........40..........60..........80.........|
..........20..........40..........60..........80..........100..........120..........140..........160..........180.....Validate Dosage against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage|3.1.0..........20..........40..........60..........80.........|
Validate Dosage against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-split|3.1.0..........20..........40..........60..........80.........|
.....200..........220..........240........|
Validate Patient against http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient|3.1.0|
Validate Practitioner against http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitioner|3.1.0..........20..........40..........60..........80.........|
Validate PractitionerRole against http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitionerrole|3.1.0..........20..........40..........60..........80..........100..........120..........140..........160..........180..........200..........220..........240..........260..........280..........300..........320.........|
Validate Organization against http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-organization|3.1.0|
Validate Device against http://hl7.org/fhir/StructureDefinition/Device|4.0.1|
Validate MedicationStatement against http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement|3.1.0|
..........20..........40..........60..........80....|
 00:02.543
Done. Times: Loading: 00:10.608, validation: 00:02.543. Memory = 558Mb

Success: 0 errors, 0 warnings, 1 notes
  Information @ Bundle.entry[0].resource.entry[3].resource.ofType(MedicationStatement).contained[0].ofType(Medication).code.coding[0] (line 174, col10): Code System URI 'urn:oid:2.51.1.1' is unknown so the code cannot be validated

**Comment by qligier** [comment]
The document is valid, it is an issue in the profile. Will have to redeploy (later today probably).

**Comment by qligier** [comment]
I've redeployed the PMP.

**Comment by arhuberg** [comment]
The attached MTP is now accepted - thanks.
