### ISSUE TITLE
MTP validation error - matchboxv3/fhir/$validate 

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#59]
I attached the results of validating an MTP and get an error – but not sure what it is referring to (it does get processed successfully).

	{
			"extension": [
				{
					"url": "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line",
					"valueInteger": 1
				}
			],
			"severity": "error",
			"code": "processing",
			"diagnostics": "Bundle.entry:Composition: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan|4.0.0-ballot)",
			"location": [
				"Bundle",
				"Line 1, Col 4914"
			]
		},

[mtp.zip](https://github.com/ahdis/ch-emed-pmp/files/12195395/mtp.zip)

**Comment by qligier** [comment]
With matchbox, I don't get any error. Which validator did you use?

**Comment by arhuberg** [comment]
https://test.ahdis.ch/matchboxv3/fhir/$validate
profile=http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan

**Comment by arhuberg** [comment]
I repeated the test again this morning and do not get any errors - just a warning about SNOMED "code": "761931002".

Is this the correct code? 

It is defined here: https://cara-ch.github.io/emed-service-guide/transactions/iti41/#publishing-a-ch-emed-epr-document

{
  "resourceType": "OperationOutcome",
  "id": "075d2396308302f435e3aa309d89f32cda2edcdd61487898a7a0967ffe6e0bfd",
  "issue": [ {
    "extension": [ {
      "url": "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line",
      "valueInteger": 0
    } ],
    "severity": "information",
    "code": "processing",
    "diagnostics": "Validation for profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan|4.0.0-ballot (2023-06-29T14:57:50+02:00) with packages: hl7.fhir.xver-extensions#0.0.13, hl7.fhir.r4.core#4.0.1, hl7.terminology#5.1.0, hl7.fhir.uv.extensions.r4#1.0.0, ihe.formatcode.fhir#1.1.0, ch.fhir.ig.ch-epr-term#2.0.9, ch.fhir.ig.ch-core#4.0.0-ballot, ch.fhir.ig.ch-emed#4.0.0-ballot Total: 6892ms powered by matchbox-engine 3.3.0, hapi-fhir 6.6.0 and org.hl7.fhir.core 6.0.1 validation parameters Parameters {doNative=false, hintAboutNonMustSupport=false, recursive=false, doDebug=false, assumeValidRestReferences=false, canDoNative=false, noExtensibleBindingMessages=false, noUnicodeBiDiControlChars=false, noInvariants=false, wantInvariantsInMessages=false, txServer='http://tx.fhir.org', lang='null', snomedCT='900000000000207008', fhirVersion='4.0.1', ig=ch.fhir.ig.ch-emed#4.0.0-ballot, questionnaireMode=CHECK, level=HINTS, mode=VALIDATION, securityChecks=false, crumbTrails=false, forPublication=false, jurisdiction=urn:iso:std:iso:3166#US, allowExampleUrls=false, locale='English', locations={}}",
    "location": [ "Line[0] Col[0]", "Line 0, Col 0" ]
  }, {
    "extension": [ {
      "url": "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line",
      "valueInteger": 1
    } ],
    "severity": "warning",
    "code": "processing",
    "diagnostics": "None of the codings provided are in the value set 'DocumentEntry.typeCode' (http://fhir.ch/ig/ch-epr-term/ValueSet/DocumentEntry.typeCode|2.0.9), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://snomed.info/sct#761931002, http://loinc.org#77603-9)",
    "location": [ "Bundle.entry[0].resource.type", "Line 1, Col 890" ]
  }, {
    "extension": [ {
      "url": "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line",
      "valueInteger": 1
    } ],
    "severity": "information",
    "code": "processing",
    "diagnostics": "Code System URI 'urn:oid:2.51.1.1' is unknown so the code cannot be validated",
    "location": [ "Bundle.entry[0].resource.entry[3].resource/*MedicationStatement/null*/.contained[0]/*Medication/med*/.code.coding[0]", "Line 1, Col 3283" ]
  } ]
}

**Comment by arhuberg** [comment]
I tried a few MTPs and encountered another validation error. Can you help diagnose this? I attached Ventolin-mtp.json and Ventolin-mtp-validation.txt
[ventolin.zip](https://github.com/ahdis/ch-emed-pmp/files/12293405/ventolin.zip)

I think this is related to our mapping of unit of measure - we used {Dose} which is defined here: http://build.fhir.org/ig/hl7ch/ch-emed/ValueSet-UnitCode.html, but not in https://ucum.org/ucum. I think there may be a few more in the ValueSet list that are not in ucum list.

**Comment by qligier** [comment]
> I repeated the test again this morning and do not get any errors - just a warning about SNOMED "code": "761931002". Is this the correct code?

Yes it is. We can't incorporate the code in ch-epr-term because it has not entered in force yet. We downgraded that check to a simple warning because of that.

**Comment by qligier** [comment]
> I tried a few MTPs and encountered another validation error. Can you help diagnose this? I attached Ventolin-mtp.json and Ventolin-mtp-validation.txt

Again, I don't have an error with this document. Not sure what is going on here.
![test ahdis ch_matchboxv3_](https://github.com/ahdis/ch-emed-pmp/assets/3299399/1564ddce-c248-4a84-841c-330c6d37f942)

> we used {Dose} which is defined here: http://build.fhir.org/ig/hl7ch/ch-emed/ValueSet-UnitCode.html, but not in https://ucum.org/ucum.

It is defined here: https://ucum.org/ucum#para-6

**Comment by arhuberg** [comment]
I repeated the Ventolin order again, and now I do NOT see those validation errors.

**Comment by arhuberg** [comment]
I do not understand why the validator was behaving as observed above (i.e. reported errors, then did not when repeated) - but I think this can be closed and we can monitor it.
