### ISSUE TITLE
Unable to open medication card

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#62]
This morning we are unable to read medication cards from the test system:

{
	  "response": {
	    "status": 500,
	    "data": {
	      "resourceType": "OperationOutcome",
	      "issue": [
	        {
	          "severity": "error",
	          "code": "processing",
	          "diagnostics": "Unexpected server error"
	        }
	      ]
	    }
	  },
	  "config": {
	    "method": "GET",
	    "url": "https://test.ahdis.ch/mag-pmp2/fhir/DocumentReference/$find-medication-list?status=current&patient.identifier=urn%3Aoid%3A2.16.756.5.30.1.191.1.0.2.1%7C22701467-5f85-4818-8cd5-202d86c4decc&format=urn%3Aoid%3A2.16.756.5.30.1.127.3.10.10%7Curn%3Ache%3Aepr%3Ach-emed%3Amedication-card%3A2022",
	    "headers": {}
	  }
	}

**Comment by arhuberg** [comment]
Permanent URL
EPRIK - I think this is the transaction that is failing...

https://test.ahdis.ch/eprik-cara/index.html#/transaction/c30f3d0c-628b-407b-8c4a-b40265f61ebe
Status
HTTP-0 Response invalid Request invalid XUA
Client
unknown
Sequence ID
c30f3d0c-628b-407b-8c4a-b40265f61ebe
Type
xds-iti18
Request Timestamp
8/30/2023, 7:48:19 AM
Response Timestamp
-

**Comment by qligier** [comment]
There was no response from the PMP, maybe a temporary network error, or the PMP was down.
Do not mind the request validation errors, the transaction is recognized as ITI-18 instead of PHARM-1 and validated as such.

**Comment by arhuberg** [comment]
I will continue to monitor it, but it is still not working from here either: https://test.ahdis.ch/mag-pmp2/#/mag

**Comment by qligier** [comment]
Seems to be up: https://pmp.posttenebrassilico.ch/pmp2/mhd/debug

From [the logs](https://pmp.posttenebrassilico.ch/pmp2/mhd/logs), it seems the requests from the MAG are correctly processed in the PMP. There seems to be an issue in the MAG itself.

**Comment by qligier** [comment]
Fixed, sorry for that bug. For a yet unknown reason, Camel parses the PMP response as byte[], while CARA's is parsed as a stream. Not sure what's going on in the network for that to happen.

**Comment by arhuberg** [comment]
Thanks. Working again.
