### ISSUE TITLE
MTP and PADV Change documents are erroring when MedicationStatement.reasonCode.text field length is >255

### ISSUE THREAD

**Issue by CheriGey** [ahdis/ch-emed-pmp#65]
MTP and PADV Change documents are failing when the MedicationStatement.reasonCode.text (Treatment Reason) length is > 255.  We have the potential to send 287 characters and couldn't find a field length limitation in the spec.

Error from the log file:
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)

**Comment by dvribeira** [comment]
I happened to notice the error as well on the logs yesterday. I have just increased this field's limit on the DB and I have created a dev issue to review all string lengths on the DB definition just in case.

Thanks!

**Comment by qligier** [comment]
Indeed, the limit should be 1024*1024 chars.

**Comment by CheriGey** [comment]
I resent my document and it posted fine, no errors.  Thanks for turning this around so quickly.
