### ISSUE TITLE
Validation of codes from value set with extensible binding (CH EMED: ActivePharmaceuticalIngredient)

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#7]
There is no information/warning in CH EMED if the code of Medication.ingredient is not included in the value set with an extensible binding.
* Should the validation give an information/warning? ([Question on Zulip](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Validation.20of.20codes.20from.20value.20sets.20with.20extensible.20binding))
* How do we handle the transformation from FHIR to CDA, respectively the validation of the CDA document
``` xml
<pharm:ingredient classCode="MMAT" determinerCode="KIND">
   <pharm:code code="387165009" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT" displayName="Enalapril maleate (substance)"/>
   <pharm:name>Énalapril maléate</pharm:name>
</pharm:ingredient>
```
```
"text": "The document '5ddd0eec-124a-40b9-aee8-a104a6441945' is not valid: Schematron error: {[[Text@0x6ff315e5: content=[(ManufacturedMaterialEntryContentModule): The value for code SHALL be selected from value set '2.16.756.5.30.1.1.11.82' ActivePharmaceuticalIngredient (DYNAMIC).]]; fpi=null; icon=null; lang=null; see=null; space=null]} in {/hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section/hl7:entry/hl7:substanceAdministration/hl7:consumable/hl7:manufacturedProduct/hl7:manufacturedMaterial/pharm:ingredient/pharm:ingredient/pharm:code}."
```

*********************
Medication.ingredient: https://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-medication.html
ValueSet (extensible): https://build.fhir.org/ig/hl7ch/ch-emed/ValueSet-ActivePharmaceuticalIngredient.html

Medication with code, which is not included in the value set: http://build.fhir.org/ig/ahdis/ch-emed-pmp/branches/validation-extensible/MedicationStatement-0-1-MedStatReniten.html
Validation (QA): http://build.fhir.org/ig/ahdis/ch-emed-pmp/branches/validation-extensible/qa.html#_scratch_ig-build-temp-94XR3V_repo_fsh-generated_resources_MedicationStatement-0-1-MedStatReniten

**Comment by pjolo** [comment]
@qligier : Yes, we would like to keep the value set. The value set contains the substances that are approved by Swissmedic. This prevents the use of substances that are not permitted. This means that if there are changes in the approval of substances in Switzerland, these will be entered in the value set. The value set cannot simply be deleted, as it is already being used by other manufacturers.

**Comment by ziegm** [comment]
raised an issue for CH EMED ballot:
https://github.com/hl7ch/ch-emed/issues/126
